#!/bin/sh

ssh-keygen -t rsa -C `whoami`@`uname -n`
ssh-add ~/.ssh/id_rsa

echo "checking for requirements"
if [ ! -f `which git` ] && [ ! -f `which curl` ]
then
	if [ -x /usr/bin/apt-get ]
	then
		echo "installing requiements..."
		sudo apt-get install git-core curl
	else
		echo "could not install pre-requisites, please install them manually"
		echo "required: git curl"
		exit
	fi
else
	echo "requirements exist, proceeding to install phase..."
fi

echo "Adding Configuration.."
git config --global user.name "nvasilakis"
git config --global user.email "nikos.ailo@gmail.com"
git config --global core.editor "vim"
git config --global color.diff "auto"
git config --global color.status "auto"
git config --global color.branch "auto"
git config --global color.interactive "auto"
git config --global diff.tool vimdiff
git config --global difftool.prompt false

if [ -d ~/.vim ]
then
        echo "updating dotfiles..."
        cd ~/.vim
	git clone git@github.com:nvasilakis/immateriia.git .
else
	mkdir -p ~/.vim
        echo "creating ~/.vim..."
        cd ~/.vim
	git clone git@github.com:nvasilakis/immateriia.git .
fi

FILES=".vimrc .bashrc .zshrc .irbrc .screenrc .ss .conkyrc" 
for i in $FILES; do 
        echo installing: ~/.vim/$i ~/$i
        rm -rf ~/$i
        ln -s ~/.vim/$i ~/$i
done

echo "installation complete"
